dist: xenial

addons:
  postgresql: 9.6
  # TODO: Add mysql addon as well

services:
  - mysql
  - rabbitmq

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  global:
    - POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=release OAREPO_VERSION=3.1.1 ES=$ES6_DOWNLOAD_URL EXTRAS=postgresql,tests SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES6_DOWNLOAD_URL EXTRAS=postgresql,tests SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES6_DOWNLOAD_URL EXTRAS=sqlite,tests
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES7_DOWNLOAD_URL EXTRAS=postgresql,tests-es7 SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES7_DOWNLOAD_URL EXTRAS=sqlite,tests-es7

python:
  - "3.7"
  - "3.8"

before_install:
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder pip-tools"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.in"
  - "pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in"
  - cat .travis-release-requirements.txt
  - mkdir /tmp/elasticsearch
  - wget -O - $ES | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - "/tmp/elasticsearch/bin/elasticsearch &"
#  - "sudo apt-get install erlang-nox rabbitmq-server"
#  - "sudo /etc/init.d/rabbitmq-server start"
  - sleep 10

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"
#  - "travis_retry pip uninstall -y invenio-oaiserver"   # problems with deps - marshmallow

script:
  - "./run-tests.sh"

after_success:
  - coveralls

#deploy:
#  provider: pypi
#  user: TODO: PYPIUSERNAME
#  password:
#    secure: TODO: PYPISECUREHASH
#  distributions: "compile_catalog sdist bdist_wheel"
#  on:
#    tags: true
#    python: "3.6"
#    repo: cis/cis-theses-repository
#    condition: $DEPLOY = true
